version: 2.1

jobs:
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: Creating workspace
          command: |
            mkdir /tmp/workspace
            echo "hello world" > output.txt
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            -  /tmp/workspace
  print_output_file:
    docker:
      - image: circle/node:13.8.0
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          cat output.txt

  print_hello:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          echo "hello"
  print_world:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          echo "world"

workflows:
  welcome:
    jobs:
    - save_hello_world_output
    - print_hello: 
        requires: [save_hello_world_output]
