version: 2.1

jobs:
  save_hello_world_output:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - run:
          name: Creating workspace
          command: |
            mkdir /tmp/workspace
            cd /tmp/workspace
            pwd
            ls
            echo "hello world" > output.txt
      - persist_to_workspace:
          root: /tmp/workspace
          paths:
            -  output.txt
  print_output_file:
    docker:
      - image: circleci/node:13.8.0
    steps:
      - attach_workspace:
          at: /tmp/workspace
      - run:
          name: Displaying contents of saved output.txt
          command: |
            cd /tmp/workspace
            pwd
            ls -lah
            cat output.txt

workflows:
  welcome:
    jobs:
    - save_hello_world_output
    - print_output_file: 
        requires: [save_hello_world_output]
